### ISSUE TITLE
How to derive the closed form for M, S, and C in squash_sin(m, s, max_action=None)

### ISSUE THREAD

**Issue by thaipduong** [nrontsis/PILCO#12]
Hi guys,
I'm trying to analytically derive the closed forms for M, S and C used in squash_sin function. Deisenroth's thesis only points to some integrations in Appendix A.1 but I don't how he came up with the form used in the code.
Do you happen to know how to derive the forms? Any pointers would be much appreciated.

Thanks.

**Comment by thaipduong** [comment]
Never mind. I figured it out. Thanks.

**Comment by hjzh4** [comment]
Hi @thaipduong, could you give me some hits on it? I am also trying to figure this out while have no clues yet.

**Comment by mdbenito** [comment]
Consider two gaussians X_i and X_j and their sines Y_i = sin X_i and Y_j = sin X_j. You want to compute the covariance E[(Y_i - EY_i) (Y_j - EY_j]. After expanding the product and simplifying a bit, one of the terms is E[Y_i Y_j]. This is the product of two sines so you can use the formula expressing it as a a difference of cosines. Use linearity and after some arithmetic you have entry ij in the covariance matrix, already looking similar to the code. The final part is to vectorise that. For this note what the convention in Tensorflow or numpy is when a column vector is added to a row vector and you are almost done.

Hope that helps!

**Comment by hjzh4** [comment]
Hey Miguel, thanks for the help!

I have a question that I think Y_i is independent with Y_j so cov(Y_i, Y_j) should be 0 while it is clearly not true wrt the code.

Could you please tell me where I am wrong?

**Comment by thaipduong** [comment]
@hjzh4 , I found my notes on this here: https://drive.google.com/file/d/1MqZMkRM6vkLJIOOhe8gXFddpMflLJvB2/view?usp=sharing
It's the same as what @mdbenito mentioned above. Hope it helps.

**Comment by hjzh4** [comment]
@thaipduong @mdbenito , thanks a lot guys! I just figured it out!
could you also take a look at issue #15 I think there is something missed in the formula for computing C
