### ISSUE TITLE
Initialisation of ExponentialReward: eye(.) vs ones(.)

### ISSUE THREAD

**Issue by ven-kyoshiro** [nrontsis/PILCO#25]
The initialisation of the weights `W` of the exponential reward has a default initialisation of `np.ones(.)`, as defined in the following line:
https://github.com/nrontsis/PILCO/blob/6ebcc7df9a8190c542445f0c82d835c94b745c8e/pilco/rewards.py#L25

But when I calculate the reward mean concentrically centered on the target, 
```
import matplotlib.pyplot as plt
from pilco.rewards import ExponentialReward
import tensorflow as tf
import numpy as np
with tf.Session(graph=tf.Graph()) as sess:
    R = ExponentialReward(state_dim=2, t=np.array([0.,0.]),W=np.ones((2,2)))
    muRs = lambda th:R.compute_reward(np.array([np.sin(th),np.cos(th)]), s=np.eye(2))
    left = [i/36*2*np.pi for i in range(36)]
    height = np.array([muRs(th)[0].eval()[0][0] for th in left])
plt.xlabel('rad')
plt.ylabel('mean of reward')
plt.plot(left, height,label='ones')
plt.legend()
```
the score is not a constant, as it can observed in the following plot:
![Unknown-1](https://user-images.githubusercontent.com/8063351/54349985-b86e1300-468f-11e9-9b02-773653a5bf67.png)

So I think np.eye(state_dim) is better, i.e. having
```python
self.W = Param(np.eye(state_dim), trainable=False) 
```
which gives the following score across theta:
![Unknown-2](https://user-images.githubusercontent.com/8063351/54350208-30d4d400-4690-11e9-9e11-5e9cd4fae07e.png)

**Comment by nrontsis** [comment]
Also, @ven-kyoshiro can you elaborate on why would you want the cost to be constant across theta? Also, it would be helpful to make the same argument with a real, simple example (like an inverted pendulum).

**Comment by ven-kyoshiro** [comment]
Thanks for kind response!! I read this [original paper](http://mlg.eng.cam.ac.uk/pub/pdf/DeiRas11.pdf) . An equation (25) in the paper was defined by using L2-Norm, so I think the state which is same distance form target should return the same reward.

**Comment by kyr-pol** [comment]
Hey @ven-kyoshiro, thanks, that's a good catch. I agree `eye(.)` would be more appropriate as the default value. In most cases we expect the user to define a reward relevant to the task at hand, but `eye(.)` seems more reasonable as the standard choice, and even in our examples the rewards used are diagonal. I think I initially went with `ones` for debugging purposes (many zero values could hide mistakes), but that's not relevant now.
