### ISSUE TITLE
Matrix contain inf or nan

### ISSUE THREAD

**Issue by jastfkjg** [nrontsis/PILCO#27]
hello, 

  when I use mgpr to predict next observation, sometimes “matrix contains infs or nans" error occurs. I find it first appear in `mgpr.py predict_given_factorizations`, with code `c = self.variance / tf.sqrt(tf.linalg.det(B))`. It turns out that tf.linalg.det(B) is negative. What should I do about this ? 

Thanks

**Comment by nrontsis** [comment]
Thanks for opening the issue. This shouldn't happen as `B` is by construction positive definite, thus its determinant must be positive. Perhaps the initial variance `s` that you are passing is not positive definite?

**Comment by jastfkjg** [comment]
Thanks. It's a prob in my code. I'll close this.
