### ISSUE TITLE
Reference for predicting with uncertain inputs with SMGPR

### ISSUE THREAD

**Issue by powertj** [nrontsis/PILCO#40]
Do you have a reference available for the derivation of prediction with uncertain inputs with a sparse GP? I haven't been able to find one anywhere.

**Comment by kyr-pol** [comment]
Hey @powertj, 
I haven't found a reference that shows specifically how to combine both, but in general they are separate procedures.  The sparse approximation used here (FITC, Snelson and Ghahramani) is based on inducing points (pseudoinputs for the GP, replacing the real data points). Once you get the approximation to the kernel according to the method for sparse GPs you are using (see par. 2.4, Sparse Approximations using Inducing Inputs, from M. Deisenroth's [thesis](https://spiral.imperial.ac.uk/bitstream/10044/1/13927/10/thesis_mpd_corrected.pdf) ), you can continue with the predictions as you would normally. 

That is why in our code only the `calculate_factorizations` function is redefined in `SMGPR`  (performing the kernel computations and inversions), while the `predict_given_factorizations` (performing the predictions with uncertain inputs) remains the same with `MGPR`. Hope this helps!
