### ISSUE TITLE
Provide example for RBF controller

### ISSUE THREAD

**Issue by voop** [nrontsis/PILCO#5]
Please provide example for using RBF controller.
In pilco 'init' function neither the controller nor the reward is assigned to the object if not 'None'
Thanks.

**Comment by kyr-pol** [comment]
Hi @voop, good catch, I'll get to it, thank you.

**Comment by nrontsis** [comment]
@kyr-pol I fixed the comment of @voop in branch `rbf_controller`.

However, it seems that the refactoring I made in the RBF controller (the one to avoid rewriting `gp0`) messed up with GPflow's optimization.

When trying to optimize the controller I get: `No variables to optimize.`

**Comment by kyr-pol** [comment]
Hm if that is the case with `Param`s inside `GPR` objects, yes it makes sense to just use the kernels. It is a bit weird and it seems worth looking into, but if we can get a quick fix we can look into it further later.

**Comment by voop** [comment]
I think if ParamList from GPFlow is used instead of simple 'list' it will be visible to the optimization.
However, changing it will cause other issues which I was not able to resolve...

**Comment by nrontsis** [comment]
Thanks @voop.  I believe that we want to use `ParamList` only for Rbf controller. This can be done by overriding the `create_models` function of `MGPR`.

I'll try to see if that works.

**Comment by nrontsis** [comment]
Okay, `ParamList` made the parameters visible to the optimiser. I still had to create a fake GPR class, where X and Y are `Param` and not `DataHolders`, as I think that `GPflow` does not optimises over `DataHolders`.

However, I am now getting NaNs on the cost of the policy. @kyr-pol can you take a look?

**Comment by kyr-pol** [comment]
Yes I will get to it later tonight and see what I can do.

**Comment by kyr-pol** [comment]
It seems that the NaNs were a numerical issue. By reducing the number of basis functions significantly (from 100 to 10, but 20 work too) the optimisation progresses. 

Still, there are frequent failures, either in the Cholesky decompositions or the controller optimisation, which appear sometimes when using the LinearController as well. We should investigate these further.

**Comment by nrontsis** [comment]
Okay, that's good news. Let's close this and open a separate issue on numerical stability.
