### ISSUE TITLE
NotImplementedError: Cannot convert a symbolic (graph mode) `DeferredTensor` to a numpy array.

### ISSUE THREAD

**Issue by shubham83183** [nrontsis/PILCO#61]
Hello,
I followed the instructions given in readme file and installed all the modules and libraries from requirements.txt. But the model runs for first iteration and it gives following error.(that is while optimisation, pilco.optimize_policy())

NotImplementedError: Cannot convert a symbolic (graph mode) `DeferredTensor` to a numpy array.

**Comment by hhdqirui** [comment]
I have the same issue. Did you manage to fix it?

**Comment by shubham83183** [comment]
Yes, I modified this file PILCO/pilco/models/pilco.py like this (I mean i changed optimizer to adam instead of Scipy by commenting out Scipy (line 84 to 91 in the file pilco.py) )
        if not self.optimizer:
            #self.optimizer = gpflow.optimizers.Scipy()
            self.optimizer = tf.optimizers.Adam()
            #self.optimizer.minimize(self.training_loss, self.trainable_variables, options=dict(maxiter=maxiter))
            self.optimizer.minimize(self.training_loss, self.trainable_variables)
        else:
            #self.optimizer.minimize(self.training_loss, self.trainable_variables, options=dict(maxiter=maxiter))
            self.optimizer.minimize(self.training_loss, self.trainable_variables)
