### ISSUE TITLE
Improve numerical stability

### ISSUE THREAD

**Issue by nrontsis** [nrontsis/PILCO#7]
Currently, we get Cholesky decomposition failures, especially in the `RBF` Controller (see #5).

We could try the following:
- Constraint the noise (jitter) parameters to a positive, sufficiently large, value, i.e. 1e-4, via use of `gpflow` `transforms`.
- Initialise the `RBF` inputs/outputs better. In my experience, the current the `np.random.rand` initialisation can lead to very bad conditioning. One option would be to use the same initialisation as the `MATLAB` implementation. E.g. in the cart-pole example they have:
```
policy.p.inputs = gaussian(mm(poli), ss(poli,poli), nc)';  % init. location of 
                                                           % basis functions
policy.p.targets = 0.1*randn(nc, length(policy.maxU));  % init. policy targets 
                                                        % (close to zero)
policy.p.hyp = log([1 1 1 1 0.7 0.7 0.7 0.7 1 0.01]');  % initialize policy
                                                        % hyper-parameters
```
Notice that they also initialise the hyper-parameters, and manually set the cost and other stuff, so this might be necessary to be done by a user for the algorithm to work.

**Comment by jamesheald** [comment]
Are you able to show working example code for adding jitter, initialising hyper-parameters etc, please. I am running into numerical issues (Cholesky decomposition, matrix inversion), which are preventing me from running PILCO on reacher-v2 in openai gym.

**Comment by kyr-pol** [comment]
This happened fairly rarely, but doesn't happen in the newer version, after many runs on various examples. Constraining the lengthscales of the RBF controller seemed to help.
